#services:
#  account-service:
#    image: account-service
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/accounts  # Подключение к существующему контейнеру
#      SPRING_DATASOURCE_USERNAME: network
#      SPRING_DATASOURCE_PASSWORD: dreamteam777*
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-docker-kafka-1:9092  # Подключение к Kafka
#      SPRING_FLYWAY_ENABLED: "true"
#      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
#      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
#    networks:
#      - kafka-docker_default
#      - microservice-network
#      - teamcity_default
#
#networks:
#  kafka-docker_default:
#    external: true
#  microservice-network:
#    external: true
#  teamcity_default:
#    external: true

services:
  account-service:
    image: account-service
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/accounts  # Подключение к существующему контейнеру
      SPRING_DATASOURCE_USERNAME: network
      SPRING_DATASOURCE_PASSWORD: dreamteam777*
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-docker-kafka-1:9092  # Подключение к Kafka
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    networks:
      - kafka-docker_default
      - microservice-network
      - teamcity_default

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-docker-kafka-1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Подключение к Zookeeper
    networks:
      - kafka-docker_default
      - microservice-network
      - teamcity_default

networks:
  kafka-docker_default:
    external: true
  microservice-network:
    external: true
  teamcity_default:
    external: true
